# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Rich Lee
tagline:          'Software Engineer'
description:      'Documenting my experiences in programming, workflows, and other technical stuff for the internet and future me.' 
url:              http://www.richmlee.com
baseurl:          /

author:
  name:           'Rich Lee'
  url:            http://www.richmlee.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
